name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          filename: static/github-metrics.*
          user: penrodlol
          config_output: json
          config_timezone: America/New_York
          committer_message: 'chore: update github metrics [skip ci]'

          # Lines
          plugin_lines: yes
