name: Posts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm install
      - name: Generate Posts
        run: node scripts/posts.mjs
      - name: Commit Changes
        run: |
          git config --global user.name "penrodlol"
          git config --global user.email "penrodlol@users.noreply.github.com"
          git add .
          git commit -m "🤖 Update Posts"
          git push
